env:
  browser: true
  es6: true
  jquery: true
  node: true

extends:
  - eslint:recommended

plugins:
  - security

root: true

rules:
  security/detect-buffer-noassert: warn
  security/detect-child-process: warn
  security/detect-disable-mustache-escape: warn
  security/detect-eval-with-expression: warn
  security/detect-new-buffer: warn
  security/detect-no-csrf-before-method-override: warn
  security/detect-non-literal-fs-filename: warn
  security/detect-non-literal-regexp: warn
  security/detect-non-literal-require: warn
  security/detect-possible-timing-attacks: warn
  security/detect-pseudoRandomBytes: warn
  security/detect-unsafe-regex: warn

  eqeqeq: error
  no-console: warn
  no-path-concat: error
  no-unused-vars: [error, {argsIgnorePattern: "^_|next"}]
  no-var: error
  one-var: [error, never]
  prefer-const: error
  quotes: [error, single]
