env:
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:node/recommended
  - plugin:security/recommended
  - prettier


plugins:
  - node
  - prettier
  - security

root: true

rules:
  node/no-unpublished-require: off

  prettier/prettier: ['error', { singleQuote: true }]

  security/detect-non-literal-fs-filename: off
  security/detect-object-injection: off

  eol-last: [error, always]
  eqeqeq: error
  no-alert: warn
  no-console: warn
  no-path-concat: error
  no-unused-vars: [error, {argsIgnorePattern: "^_|err|event|next|reject"}]
  no-var: error
  one-var: [error, never]
  prefer-const: error
  quotes: [error, single, {avoidEscape: true}]
